//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ZelloVoice.Web.SessionService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SessionWSSoap", Namespace="http://telvisant.trimble.com/WebServices/")]
    public partial class SessionWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Login1OperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCapabilitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCapabilityCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCapabilitiesOfCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCapabilityGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerUserDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerUserDetails2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuditTraceStartOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuditTraceStopOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuditTraceLogOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SessionWS() {
            this.Url = global::ZelloVoice.Web.Properties.Settings.Default.ZelloVoice_Web_SessionService_SessionWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event Login1CompletedEventHandler Login1Completed;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event GetCapabilitiesCompletedEventHandler GetCapabilitiesCompleted;
        
        /// <remarks/>
        public event GetCapabilityCategoriesCompletedEventHandler GetCapabilityCategoriesCompleted;
        
        /// <remarks/>
        public event GetCapabilitiesOfCategoryCompletedEventHandler GetCapabilitiesOfCategoryCompleted;
        
        /// <remarks/>
        public event GetCapabilityGroupsCompletedEventHandler GetCapabilityGroupsCompleted;
        
        /// <remarks/>
        public event GetCustomerUserDetailsCompletedEventHandler GetCustomerUserDetailsCompleted;
        
        /// <remarks/>
        public event GetCustomerUserDetails2CompletedEventHandler GetCustomerUserDetails2Completed;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event AuditTraceStartCompletedEventHandler AuditTraceStartCompleted;
        
        /// <remarks/>
        public event AuditTraceStopCompletedEventHandler AuditTraceStopCompleted;
        
        /// <remarks/>
        public event AuditTraceLogCompletedEventHandler AuditTraceLogCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/Login", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SessionID")]
        public string Login(string CustomerName, string Username, string Password, string SdkOrganization, string SdkDeveloperID, string SdkPassword, out LoginResult LoginResult) {
            object[] results = this.Invoke("Login", new object[] {
                        CustomerName,
                        Username,
                        Password,
                        SdkOrganization,
                        SdkDeveloperID,
                        SdkPassword});
            LoginResult = ((LoginResult)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string CustomerName, string Username, string Password, string SdkOrganization, string SdkDeveloperID, string SdkPassword) {
            this.LoginAsync(CustomerName, Username, Password, SdkOrganization, SdkDeveloperID, SdkPassword, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string CustomerName, string Username, string Password, string SdkOrganization, string SdkDeveloperID, string SdkPassword, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        CustomerName,
                        Username,
                        Password,
                        SdkOrganization,
                        SdkDeveloperID,
                        SdkPassword}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="Login1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/Login2", RequestElementName="Login2", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseElementName="Login2Response", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SessionID")]
        public string Login(string CustomerName, string Username, string Password, string UserCulture, out LoginResult LoginResult) {
            object[] results = this.Invoke("Login1", new object[] {
                        CustomerName,
                        Username,
                        Password,
                        UserCulture});
            LoginResult = ((LoginResult)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Login1Async(string CustomerName, string Username, string Password, string UserCulture) {
            this.Login1Async(CustomerName, Username, Password, UserCulture, null);
        }
        
        /// <remarks/>
        public void Login1Async(string CustomerName, string Username, string Password, string UserCulture, object userState) {
            if ((this.Login1OperationCompleted == null)) {
                this.Login1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogin1OperationCompleted);
            }
            this.InvokeAsync("Login1", new object[] {
                        CustomerName,
                        Username,
                        Password,
                        UserCulture}, this.Login1OperationCompleted, userState);
        }
        
        private void OnLogin1OperationCompleted(object arg) {
            if ((this.Login1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Login1Completed(this, new Login1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/Logout", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Logout(string SessionID) {
            this.Invoke("Logout", new object[] {
                        SessionID});
        }
        
        /// <remarks/>
        public void LogoutAsync(string SessionID) {
            this.LogoutAsync(SessionID, null);
        }
        
        /// <remarks/>
        public void LogoutAsync(string SessionID, object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[] {
                        SessionID}, this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/GetCapabilities", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Capabilities")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Capability")]
        public string[] GetCapabilities(string SessionID) {
            object[] results = this.Invoke("GetCapabilities", new object[] {
                        SessionID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCapabilitiesAsync(string SessionID) {
            this.GetCapabilitiesAsync(SessionID, null);
        }
        
        /// <remarks/>
        public void GetCapabilitiesAsync(string SessionID, object userState) {
            if ((this.GetCapabilitiesOperationCompleted == null)) {
                this.GetCapabilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCapabilitiesOperationCompleted);
            }
            this.InvokeAsync("GetCapabilities", new object[] {
                        SessionID}, this.GetCapabilitiesOperationCompleted, userState);
        }
        
        private void OnGetCapabilitiesOperationCompleted(object arg) {
            if ((this.GetCapabilitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCapabilitiesCompleted(this, new GetCapabilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/GetCapabilityCategories", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CapabilityCategory[] GetCapabilityCategories(string SessionID) {
            object[] results = this.Invoke("GetCapabilityCategories", new object[] {
                        SessionID});
            return ((CapabilityCategory[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCapabilityCategoriesAsync(string SessionID) {
            this.GetCapabilityCategoriesAsync(SessionID, null);
        }
        
        /// <remarks/>
        public void GetCapabilityCategoriesAsync(string SessionID, object userState) {
            if ((this.GetCapabilityCategoriesOperationCompleted == null)) {
                this.GetCapabilityCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCapabilityCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetCapabilityCategories", new object[] {
                        SessionID}, this.GetCapabilityCategoriesOperationCompleted, userState);
        }
        
        private void OnGetCapabilityCategoriesOperationCompleted(object arg) {
            if ((this.GetCapabilityCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCapabilityCategoriesCompleted(this, new GetCapabilityCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/GetCapabilitiesOfCategory", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Capabilities")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Capability")]
        public string[] GetCapabilitiesOfCategory(string SessionID, string CategoryToken) {
            object[] results = this.Invoke("GetCapabilitiesOfCategory", new object[] {
                        SessionID,
                        CategoryToken});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCapabilitiesOfCategoryAsync(string SessionID, string CategoryToken) {
            this.GetCapabilitiesOfCategoryAsync(SessionID, CategoryToken, null);
        }
        
        /// <remarks/>
        public void GetCapabilitiesOfCategoryAsync(string SessionID, string CategoryToken, object userState) {
            if ((this.GetCapabilitiesOfCategoryOperationCompleted == null)) {
                this.GetCapabilitiesOfCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCapabilitiesOfCategoryOperationCompleted);
            }
            this.InvokeAsync("GetCapabilitiesOfCategory", new object[] {
                        SessionID,
                        CategoryToken}, this.GetCapabilitiesOfCategoryOperationCompleted, userState);
        }
        
        private void OnGetCapabilitiesOfCategoryOperationCompleted(object arg) {
            if ((this.GetCapabilitiesOfCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCapabilitiesOfCategoryCompleted(this, new GetCapabilitiesOfCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/GetCapabilityGroups", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("CapabilityGroups")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Group")]
        public IDNamePair[] GetCapabilityGroups(string SessionID) {
            object[] results = this.Invoke("GetCapabilityGroups", new object[] {
                        SessionID});
            return ((IDNamePair[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCapabilityGroupsAsync(string SessionID) {
            this.GetCapabilityGroupsAsync(SessionID, null);
        }
        
        /// <remarks/>
        public void GetCapabilityGroupsAsync(string SessionID, object userState) {
            if ((this.GetCapabilityGroupsOperationCompleted == null)) {
                this.GetCapabilityGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCapabilityGroupsOperationCompleted);
            }
            this.InvokeAsync("GetCapabilityGroups", new object[] {
                        SessionID}, this.GetCapabilityGroupsOperationCompleted, userState);
        }
        
        private void OnGetCapabilityGroupsOperationCompleted(object arg) {
            if ((this.GetCapabilityGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCapabilityGroupsCompleted(this, new GetCapabilityGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/GetCustomerUserDetails", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerUserDetails GetCustomerUserDetails(string SessionID) {
            object[] results = this.Invoke("GetCustomerUserDetails", new object[] {
                        SessionID});
            return ((CustomerUserDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerUserDetailsAsync(string SessionID) {
            this.GetCustomerUserDetailsAsync(SessionID, null);
        }
        
        /// <remarks/>
        public void GetCustomerUserDetailsAsync(string SessionID, object userState) {
            if ((this.GetCustomerUserDetailsOperationCompleted == null)) {
                this.GetCustomerUserDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerUserDetailsOperationCompleted);
            }
            this.InvokeAsync("GetCustomerUserDetails", new object[] {
                        SessionID}, this.GetCustomerUserDetailsOperationCompleted, userState);
        }
        
        private void OnGetCustomerUserDetailsOperationCompleted(object arg) {
            if ((this.GetCustomerUserDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerUserDetailsCompleted(this, new GetCustomerUserDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/GetCustomerUserDetails2", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetCustomerUserDetails2(string SessionID) {
            object[] results = this.Invoke("GetCustomerUserDetails2", new object[] {
                        SessionID});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerUserDetails2Async(string SessionID) {
            this.GetCustomerUserDetails2Async(SessionID, null);
        }
        
        /// <remarks/>
        public void GetCustomerUserDetails2Async(string SessionID, object userState) {
            if ((this.GetCustomerUserDetails2OperationCompleted == null)) {
                this.GetCustomerUserDetails2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerUserDetails2OperationCompleted);
            }
            this.InvokeAsync("GetCustomerUserDetails2", new object[] {
                        SessionID}, this.GetCustomerUserDetails2OperationCompleted, userState);
        }
        
        private void OnGetCustomerUserDetails2OperationCompleted(object arg) {
            if ((this.GetCustomerUserDetails2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerUserDetails2Completed(this, new GetCustomerUserDetails2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/ChangePassword", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ChangePassword(string SessionID, string OldPassword, string NewPassword) {
            this.Invoke("ChangePassword", new object[] {
                        SessionID,
                        OldPassword,
                        NewPassword});
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string SessionID, string OldPassword, string NewPassword) {
            this.ChangePasswordAsync(SessionID, OldPassword, NewPassword, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string SessionID, string OldPassword, string NewPassword, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        SessionID,
                        OldPassword,
                        NewPassword}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/Ping", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Ping(string SessionID) {
            this.Invoke("Ping", new object[] {
                        SessionID});
        }
        
        /// <remarks/>
        public void PingAsync(string SessionID) {
            this.PingAsync(SessionID, null);
        }
        
        /// <remarks/>
        public void PingAsync(string SessionID, object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[] {
                        SessionID}, this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/AuditTraceStart", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RequestID")]
        public long AuditTraceStart(string SessionID, string AuditName, [System.Xml.Serialization.XmlArrayItemAttribute("ID", IsNullable=false)] long[] AssetIDs, System.DateTime StartDate, System.DateTime EndDate, string AdditionalInformation) {
            object[] results = this.Invoke("AuditTraceStart", new object[] {
                        SessionID,
                        AuditName,
                        AssetIDs,
                        StartDate,
                        EndDate,
                        AdditionalInformation});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void AuditTraceStartAsync(string SessionID, string AuditName, long[] AssetIDs, System.DateTime StartDate, System.DateTime EndDate, string AdditionalInformation) {
            this.AuditTraceStartAsync(SessionID, AuditName, AssetIDs, StartDate, EndDate, AdditionalInformation, null);
        }
        
        /// <remarks/>
        public void AuditTraceStartAsync(string SessionID, string AuditName, long[] AssetIDs, System.DateTime StartDate, System.DateTime EndDate, string AdditionalInformation, object userState) {
            if ((this.AuditTraceStartOperationCompleted == null)) {
                this.AuditTraceStartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuditTraceStartOperationCompleted);
            }
            this.InvokeAsync("AuditTraceStart", new object[] {
                        SessionID,
                        AuditName,
                        AssetIDs,
                        StartDate,
                        EndDate,
                        AdditionalInformation}, this.AuditTraceStartOperationCompleted, userState);
        }
        
        private void OnAuditTraceStartOperationCompleted(object arg) {
            if ((this.AuditTraceStartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuditTraceStartCompleted(this, new AuditTraceStartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/AuditTraceStop", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AuditTraceStop(string SessionID, long RequestID) {
            this.Invoke("AuditTraceStop", new object[] {
                        SessionID,
                        RequestID});
        }
        
        /// <remarks/>
        public void AuditTraceStopAsync(string SessionID, long RequestID) {
            this.AuditTraceStopAsync(SessionID, RequestID, null);
        }
        
        /// <remarks/>
        public void AuditTraceStopAsync(string SessionID, long RequestID, object userState) {
            if ((this.AuditTraceStopOperationCompleted == null)) {
                this.AuditTraceStopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuditTraceStopOperationCompleted);
            }
            this.InvokeAsync("AuditTraceStop", new object[] {
                        SessionID,
                        RequestID}, this.AuditTraceStopOperationCompleted, userState);
        }
        
        private void OnAuditTraceStopOperationCompleted(object arg) {
            if ((this.AuditTraceStopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuditTraceStopCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://telvisant.trimble.com/WebServices/AuditTraceLog", RequestNamespace="http://telvisant.trimble.com/WebServices/", ResponseNamespace="http://telvisant.trimble.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AuditTraceLog(string SessionID, string AuditName, System.DateTime ExecutionStart, System.DateTime ExecutionEnd, [System.Xml.Serialization.XmlArrayItemAttribute("ID", IsNullable=false)] long[] AssetIDs, System.DateTime StartDate, System.DateTime EndDate, string AdditionalInformation) {
            this.Invoke("AuditTraceLog", new object[] {
                        SessionID,
                        AuditName,
                        ExecutionStart,
                        ExecutionEnd,
                        AssetIDs,
                        StartDate,
                        EndDate,
                        AdditionalInformation});
        }
        
        /// <remarks/>
        public void AuditTraceLogAsync(string SessionID, string AuditName, System.DateTime ExecutionStart, System.DateTime ExecutionEnd, long[] AssetIDs, System.DateTime StartDate, System.DateTime EndDate, string AdditionalInformation) {
            this.AuditTraceLogAsync(SessionID, AuditName, ExecutionStart, ExecutionEnd, AssetIDs, StartDate, EndDate, AdditionalInformation, null);
        }
        
        /// <remarks/>
        public void AuditTraceLogAsync(string SessionID, string AuditName, System.DateTime ExecutionStart, System.DateTime ExecutionEnd, long[] AssetIDs, System.DateTime StartDate, System.DateTime EndDate, string AdditionalInformation, object userState) {
            if ((this.AuditTraceLogOperationCompleted == null)) {
                this.AuditTraceLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuditTraceLogOperationCompleted);
            }
            this.InvokeAsync("AuditTraceLog", new object[] {
                        SessionID,
                        AuditName,
                        ExecutionStart,
                        ExecutionEnd,
                        AssetIDs,
                        StartDate,
                        EndDate,
                        AdditionalInformation}, this.AuditTraceLogOperationCompleted, userState);
        }
        
        private void OnAuditTraceLogOperationCompleted(object arg) {
            if ((this.AuditTraceLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuditTraceLogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telvisant.trimble.com/WebServices/")]
    public enum LoginResult {
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        FailureInvalidCustomer,
        
        /// <remarks/>
        FailureInvalidUserName,
        
        /// <remarks/>
        FailureInvalidPassword,
        
        /// <remarks/>
        FailureIneffectiveCustomer,
        
        /// <remarks/>
        FailureIneffectiveUser,
        
        /// <remarks/>
        FailureUserLockout,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        SuccessPasswordExpired,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telvisant.trimble.com/WebServices/")]
    public partial class CapabilityCategory {
        
        private string categoryTokenField;
        
        private string categoryDescField;
        
        /// <remarks/>
        public string CategoryToken {
            get {
                return this.categoryTokenField;
            }
            set {
                this.categoryTokenField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryDesc {
            get {
                return this.categoryDescField;
            }
            set {
                this.categoryDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telvisant.trimble.com/WebServices/")]
    public partial class User {
        
        private long userIDField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string emailAddressField;
        
        private string standardTimeZoneNameField;
        
        private bool lockedField;
        
        private string aliasNameField;
        
        private bool showChannelCallsInVoiceActivityLogField;
        
        /// <remarks/>
        public long UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string StandardTimeZoneName {
            get {
                return this.standardTimeZoneNameField;
            }
            set {
                this.standardTimeZoneNameField = value;
            }
        }
        
        /// <remarks/>
        public bool Locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ShowChannelCallsInVoiceActivityLog {
            get {
                return this.showChannelCallsInVoiceActivityLogField;
            }
            set {
                this.showChannelCallsInVoiceActivityLogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telvisant.trimble.com/WebServices/")]
    public partial class CustomerUserDetails {
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string emailAddressField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telvisant.trimble.com/WebServices/")]
    public partial class IDNamePair {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public LoginResult LoginResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResult)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void Login1CompletedEventHandler(object sender, Login1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Login1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Login1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public LoginResult LoginResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResult)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LogoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCapabilitiesCompletedEventHandler(object sender, GetCapabilitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCapabilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCapabilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCapabilityCategoriesCompletedEventHandler(object sender, GetCapabilityCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCapabilityCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCapabilityCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CapabilityCategory[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CapabilityCategory[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCapabilitiesOfCategoryCompletedEventHandler(object sender, GetCapabilitiesOfCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCapabilitiesOfCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCapabilitiesOfCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCapabilityGroupsCompletedEventHandler(object sender, GetCapabilityGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCapabilityGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCapabilityGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDNamePair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDNamePair[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCustomerUserDetailsCompletedEventHandler(object sender, GetCustomerUserDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerUserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerUserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerUserDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerUserDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCustomerUserDetails2CompletedEventHandler(object sender, GetCustomerUserDetails2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerUserDetails2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerUserDetails2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void PingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AuditTraceStartCompletedEventHandler(object sender, AuditTraceStartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuditTraceStartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuditTraceStartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AuditTraceStopCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AuditTraceLogCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591